FROM python:3.10-alpine
RUN apk add --no-cache gcc musl-dev g++ libffi-dev openblas-dev
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5001
CMD ["python", "app.py"]